version: "3"

services:
  # https://hub.docker.com/_/mysql
  mysql:
    image: mysql:8.0.28
    container_name: mysql
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: subwork
      MYSQL_PASSWORD: subwork
      TZ: "Asia/Tokyo"
    volumes:
      - "mysql-data:/var/lib/mysql"
      - ./servers/mysql/conf.d:/etc/mysql/conf.d

  # https://hub.docker.com/_/adminer
  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    hostname: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

  # https://hub.docker.com/r/opensearchproject/opensearch
  # https://opensearch.org/docs/latest/opensearch/install/docker/
  # TODO: sudo sysctl -w vm.max_map_count=262144
  opensearch:
    # image: opensearchproject/opensearch:1.1.0
    build: servers/opensearch/
    container_name: opensearch
    hostname: opensearch
    environment:
      - "discovery.type=single-node"
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "bootstrap.memory_lock=true"
    volumes:
      - "opensearch-data:/usr/share/opensearch/data"
    ports:
      - "9200:9200"

  # https://hub.docker.com/r/opensearchproject/opensearch-dashboards
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:1.3.0
    container_name: opensearch-dashboards
    environment:
      OPENSEARCH_HOSTS: "https://opensearch:9200"
    ports:
      - 5601:5601

volumes:
  mysql-data:
  opensearch-data: